targets = ["//:optional"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.67.0"